### ISSUE TITLE
Log & Write data to file

### ISSUE THREAD

**Issue by skamoen** [skamoen/IN4253ET-gyroscope#3]
The data coming from the gyroscope needs to be logged and written to a file for processing

**Comment by hendrahc** [comment]
added function to write gyroscope data to file
file location: storage/gyro/gyro_data.txt
format: time;roll;pitch;yawn;relative

**Comment by hesahesa** [comment]
added this functionality to the BackgroundListenerService.java file to continously log to file in the background (when the app is not opened)
